import { defineConfig } from 'oxlint';
import core from 'ultracite/oxlint/core';
import react from 'ultracite/oxlint/react';

export default defineConfig({
  extends: [core, react],
  ignorePatterns: core.ignorePatterns,
  rules: {
    'class-methods-use-this': 'off',
    'prefer-destructuring': 'off',
    'promise/prefer-await-to-callbacks': 'off',
    'promise/prefer-await-to-then': 'off',
    'require-await': 'off',
    'sort-keys': 'off',
    'func-style': 'off',
    'typescript/no-non-null-assertion': 'off',
    'typescript/no-invalid-void-type': 'off',
    'typescript/no-explicit-any': 'off',
    'typescript/no-dynamic-delete': 'off',
    'typescript/prefer-for-of': 'off',
    'eslint/complexity': 'off',
    'eslint/no-warning-comments': 'off',
    'eslint/no-negated-condition': 'off',
    'eslint/no-nested-ternary': 'off',
    'unicorn/no-nested-ternary': 'off',
    'eslint/no-use-before-define': 'off',
    'eslint/prefer-named-capture-group': 'off',
    'eslint/require-unicode-regexp': 'off',
    'eslint/prefer-promise-reject-errors': 'off',
    'eslint/no-inline-comments': 'off',
    'unicorn/no-negated-condition': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/prefer-ternary': 'off',
    'unicorn/prefer-add-event-listener': 'off',
    'unicorn/consistent-function-scoping': 'off',
    'unicorn/no-lonely-if': 'off',
    'unicorn/no-this-assignment': 'off',
    'oxc/no-barrel-file': 'off',
    'react-perf/jsx-no-jsx-as-prop': 'off',
  },
});
